@port={{$dotenv PORT}}
@host=http://localhost:{{port}}

### GET /test

GET {{host}}/lists/2

### POST /test

POST {{host}}/lists
Content-Type: application/json

{
    "name": "Doing"
}

###

PATCH {{host}}/lists/2
Content-Type: application/json

{
    "name": "Done"
}

###

DELETE {{host}}/lists/2