@port={{$dotenv PORT}}
@host=http://localhost:{{port}}

### GET /test

GET {{host}}/tags

### POST /test

POST {{host}}/cards
Content-Type: application/json

{
    "content": "Carte test",
    "color": "#f0f",
    "position": 1,
    "list_id": 1
}

###

PATCH {{host}}/cards/3
Content-Type: application/json

{
    "content": "Carte à supprimer"
}

###

DELETE {{host}}/cards/3